version: '2'
services:
  easypay-app:
    image: easypay
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://easypay-postgresql:5432/easypay
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 5001:5001
  easypay-postgresql:
    extends:
      file: postgresql.yml
      service: easypay-postgresql
